name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          webhook: https://hook.us1.make.com/ekp5ssdc5mkvor4qjxnkn3w6m93gq6sb
          token: ${{ secrets.GITHUB_TOKEN }}
          event: ${{ toJSON(github.event) }}
